site_name: Coinmarch
site_url: https://arcticblizzard.github.io/Coinmarch/
theme:
  name: slate
  navigation_depth: 3
extra_css:
  - styles/overrides.css

plugins:
  - redirects:
      redirect_maps:
        index.md : player-introduction/welcome.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Welcome: player-introduction/welcome.md
  - Overview: player-introduction/system-overview.md
  - Character Creation:
    - Guide: player-introduction/character-creation/character-creation.md
    - Basic Careers: player-introduction/character-creation/basic-careers.md
    - Knacks: player-introduction/character-creation/knacks.md
  - Map: map.md
  - Locations:
    - Lower Kolnmark: locations/LowerKolnmark.md
    - Upper Kolnmark: locations/UpperKolnmark.md