site_name: Coinmarch
site_url: https://arcticblizzard.github.io/Coinmarch/
theme:
  name: slate
  navigation_depth: 3
extra_css:
  - styles/overrides.css
  - styles/campaign-frame.css

plugins:
  - redirects:
      redirect_maps:
        index.md : player-introduction/welcome.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
nav:
  - Welcome: 
    - Introduction: player-introduction/welcome.md
    - Campaign Frame: player-introduction/campaign-frame.md
  - Overview: 
    - Basic Systems: player-introduction/system-overview.md
    - Skill Challenges: player-introduction/skill-challenges.md
  - Character Creation:
    - Guide: player-introduction/character-creation/character-creation.md
    - Basic Careers: player-introduction/character-creation/basic-careers.md
    - Knacks: player-introduction/character-creation/knacks.md
  - The Setting:
    - The City: locations/Kolnmark.md
    - Factions: factions/overview.md
