site_name: Coinmarch
site_url: https://arcticblizzard.github.io/Coinmarch/
theme:
  name: material
  logo: images/Coinmarch_Stencil.png
  palette:
    scheme: slate
    primary: amber
  font:
    text: 'Cardo'
    code: Fira Code
    headings: Cinzel
  features:
    - navigation.tabs
    - toc.integrate
extra_css:
  - styles/overrides.css
  - styles/campaign-frame.css

plugins:
  - search
  - redirects:
      redirect_maps:
        index.md : player-introduction/welcome.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.tabbed:
      alternate_style: true
nav:
  - Welcome: 
    - Introduction: player-introduction/welcome.md
    - Campaign Frame: player-introduction/campaign-frame.md
  - System Overview: 
    - Basic Systems: player-introduction/system-overview.md
    - Skill Challenges: player-introduction/skill-challenges.md
  - Character Creation:
    - Guide: player-introduction/character-creation/character-creation.md
    - Basic Careers: player-introduction/character-creation/basic-careers.md
    - Knacks: player-introduction/character-creation/knacks.md
  - The Setting:
    - The City: locations/Kolnmark.md
    - Factions: factions/overview.md
