site_name: Coinmarch
site_url: https://arcticblizzard.github.io/Coinmarch/
theme:
  name: slate
  navigation_depth: 3
extra_css:
  - styles/overrides.css

plugins:
  - redirects:
      redirect_maps:
        index.md : player-introduction/welcome.md

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
nav:
  - Welcome: player-introduction/welcome.md
  - Overview: player-introduction/system-overview.md
  - Character Creation:
    - Guide: player-introduction/character-creation/character-creation.md
    - Basic Careers: player-introduction/character-creation/basic-careers.md
    - Knacks: player-introduction/character-creation/knacks.md
  - Map: map.md
  - Locations:
    - Lower Kolnmark: locations/LowerKolnmark.md
      #- Overview: locations/LowerKolnmark.md
      #- Bargebreaker Island: locations/districts/Bargebreaker_Island.md
      #- Callus Run: locations/districts/Callus_Run.md
      #- Caskside: locations/districts/Caskside.md
      #- Cliff Cove: locations/districts/Cliff_Cove.md
      #- "Clerk's Ward": locations/districts/Clerk's_Ward.md
      #- Coinrest: locations/districts/Coinrest.md
      #- Dockshade: locations/districts/Dockshade.md
      #- "Eastchain Docks": locations/districts/Eastchain_Docks.md
      #- "Eastcliff Row": locations/districts/Eastcliff_Row.md
      #- Gatefold: locations/districts/Gatefold.md
      #- Garrison Row: locations/districts/Garrison_Row.md
      #- Hearthrow: locations/districts/Hearthrow.md
      #- Ironhook: locations/districts/Ironhook.md
      #- Newbrick Ward: locations/districts/Newbrick_Ward.md
      #- Pilgrim's Way: locations/districts/Pilgrim's_Way.md
      #- Tumbledown: locations/districts/Tumbledown.md
      #- The Point: locations/districts/The_Point.md
      #- The Stumble: locations/districts/The_Stumble.md
      #- The Tangle: locations/districts/The_Tangle.md
    - Upper Kolnmark: locations/UpperKolnmark.md
      #- Overview: locations/UpperKolnmark.md
      #- Bannercrest: locations/districts/Bannercrest.md
      #- Crafthallow: locations/districts/Crafthallow.md
      #- Dawnwatch: locations/districts/Dawnwatch.md
      #- Eastmere: locations/districts/Eastmere.md
      #- "Envoy's Rest": locations/districts/Envoy's_Rest.md
      #- Goldedge: locations/districts/Goldedge.md
      #- Highforge: locations/districts/Highforge.md
      #- Highmarch: locations/districts/Highmarch.md
      #- Swordcrest: locations/districts/Swordcrest.md
      #- Twinreach: locations/districts/Twinreach.md
      #- "Velvet Court": locations/districts/Velvet_Court.md
      #- Windrest: locations/districts/Windrest.md